[package]
name = "geode"
version = "0.3.0"
authors = ["HJfod <dreadrollmusic@gmail.com>", "Camila314 <ilaca314@gmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
colored = "2"
dirs = "4.0.0"
git2 = "0.13.25"
glob = "0.3.0"
image = "0.24.3"
path-absolutize = "3.0.11"
plist = "1.3.1"
rustyline = "9.1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
sha256 = "1.0.3"
texture_packer = "0.24.0"
walkdir = "2"
zip = "0.5.13"

[build-dependencies]
winres = "0.1.12"
